name: Publish package

on:
  release:
    types: [created]

jobs:
  publish-testpypi:
    if: startsWith(github.event.release.tag_name, 'test-')
    uses: ./.github/workflows/publish-testpypi.yaml
    permissions:
      id-token: write # Required for OIDC authentication in the called workflow

  publish-pypi:
    if: startsWith(github.event.release.tag_name, 'release-')
    uses: ./.github/workflows/publish-pypi.yaml
    permissions:
      id-token: write # Required for OIDC authentication in the called workflow
